Feature: Test

  Scenario: Buy product without registration
    Given Open Store
    Then Click on '//img[@class="js-responsive-image" and @title="Men"]'
    Then Click on text 'Jackson Tee SS mint leather M'
    Then Click on '//form[@id="addToCartForm"]//button'
    Then Click on '//div[@id="addToCartLayer"]/a[@class="btn btn-primary btn-block add-to-cart-button"]'
    Then Click on '//div[@class="cart__actions"]//button[@class="btn btn-primary btn-block btn--continue-checkout js-continue-checkout-button"]'
    Then Type to '//input[@id="guest.email"]' text 'whespeer@yandex.ru'
    Then Type to '//input[@id="guest.confirm.email"]' text 'whespeer@yandex.ru'
    Then Click on '//*[@id="guestForm"]/div[3]/button'
    Then Set select '//*[@id="address.country"]' text 'Guernsey'
    Then Set select '//*[@id="address.title"]' text 'Mr.'
    Then Type to '//input[@id="address.firstName"]' text 'Alexander'
    Then Type to '//input[@id="address.surname"]' text 'Ivanov'
    Then Type to '//input[@id="address.line1"]' text 'chelyabinskline'
    Then Type to '//input[@id="address.townCity"]' text 'Cheblyainsk'
    Then Type to '//input[@id="address.postcode"]' text '454000'
    Then Click on '//*[@id="addressSubmit"]'
    Then Click on '//*[@id="deliveryMethodSubmit"]'
    Then Set select '//*[@id="card_cardType"]' text 'Visa'
    Then Type to '//input[@id="card_accountNumber"]' text '1234567890123456'
    Then Set select '//*[@id="ExpiryMonth"]' text '03'
    Then Set select '//*[@id="ExpiryYear"]' text '2023'
    Then Type to '//input[@id="card_cvNumber"]' text '123'
    Then Click on '/html/body/main/div[3]/div/div[1]/div[2]/div/button'
    Then Click on '//*[@id="Terms1"]'
    Then Click on '//*[@id="placeOrder"]'

  Scenario: Registration on online-store and buy product
    Given Open Store
    Then Click on '/html/body/main/header/nav[1]/div/div[2]/div/ul/li[2]/a'
    Then Set select '//*[@id="register.title"]' text 'Mr.'
    Then Type to '//input[@id="register.firstName"]' text 'Alexander'
    Then Type to '//input[@id="register.lastName"]' text 'Ivanov'
    Then Type to '//input[@id="register.email"]' text '{{randomLetters}}@mail.ru'
    Then Type to '//input[@id="password"]' text 'qwerty123'
    Then Type to '//input[@id="register.checkPwd"]' text 'qwerty123'
    Then Click on '//*[@id="registerChkTermsConditions"]'
    Then Click on '//*[@id="registerForm"]/div[11]/button'
    Then Click on '//img[@class="js-responsive-image" and @title="Men"]'
    Then Click on text 'Jackson Tee SS mint leather M'
    Then Click on '//form[@id="addToCartForm"]//button'
    Then Click on '//div[@id="addToCartLayer"]/a[@class="btn btn-primary btn-block add-to-cart-button"]'
    Then Click on '//div[@class="cart__actions"]//button[@class="btn btn-primary btn-block btn--continue-checkout js-continue-checkout-button"]'
    Then Set select '//*[@id="address.country"]' text 'Isle of Man'
    Then Set select '//*[@id="address.title"]' text 'Mr.'
    Then Type to '//input[@id="address.firstName"]' text 'Alexander'
    Then Type to '//input[@id="address.surname"]' text 'Ivanov'
    Then Type to '//input[@id="address.line1"]' text 'chelyabinskline'
    Then Type to '//input[@id="address.townCity"]' text 'Cheblyainsk'
    Then Type to '//input[@id="address.postcode"]' text '454000'
    Then Click on '//*[@id="addressSubmit"]'
    Then Click on '//*[@id="deliveryMethodSubmit"]'
    Then Set select '//*[@id="card_cardType"]' text 'Visa'
    Then Type to '//input[@id="card_accountNumber"]' text '1234567890123456'
    Then Set select '//*[@id="ExpiryMonth"]' text '03'
    Then Set select '//*[@id="ExpiryYear"]' text '2023'
    Then Type to '//input[@id="card_cvNumber"]' text '123'
    Then Click on '/html/body/main/div[3]/div/div[1]/div[2]/div/button'
    Then Click on '//*[@id="Terms1"]'
    Then Click on '//*[@id="placeOrder"]'
